heat_template_version: 2016-04-08
description: A HEAT template

parameters:
  image:
    type: string
  flavor:
    type: string
  key_name:
    type: string
  public_net:
    type: string
  private_net:
    type: string        
  private_subnet:
    type: string

resources:
